// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestinationEndpoint) DeepCopyInto(out *DestinationEndpoint) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestinationEndpoint.
func (in *DestinationEndpoint) DeepCopy() *DestinationEndpoint {
	if in == nil {
		return nil
	}
	out := new(DestinationEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReachabilityTest) DeepCopyInto(out *ReachabilityTest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReachabilityTest.
func (in *ReachabilityTest) DeepCopy() *ReachabilityTest {
	if in == nil {
		return nil
	}
	out := new(ReachabilityTest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReachabilityTest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReachabilityTestList) DeepCopyInto(out *ReachabilityTestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReachabilityTest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReachabilityTestList.
func (in *ReachabilityTestList) DeepCopy() *ReachabilityTestList {
	if in == nil {
		return nil
	}
	out := new(ReachabilityTestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReachabilityTestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReachabilityTestSpec) DeepCopyInto(out *ReachabilityTestSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.Destinations != nil {
		in, out := &in.Destinations, &out.Destinations
		*out = make([]DestinationEndpoint, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReachabilityTestSpec.
func (in *ReachabilityTestSpec) DeepCopy() *ReachabilityTestSpec {
	if in == nil {
		return nil
	}
	out := new(ReachabilityTestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReachabilityTestStatus) DeepCopyInto(out *ReachabilityTestStatus) {
	*out = *in
	if in.TestStatus != nil {
		in, out := &in.TestStatus, &out.TestStatus
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReachabilityTestStatus.
func (in *ReachabilityTestStatus) DeepCopy() *ReachabilityTestStatus {
	if in == nil {
		return nil
	}
	out := new(ReachabilityTestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceEndpoint) DeepCopyInto(out *SourceEndpoint) {
	*out = *in
	if in.SourceSelector != nil {
		in, out := &in.SourceSelector, &out.SourceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceEndpoint.
func (in *SourceEndpoint) DeepCopy() *SourceEndpoint {
	if in == nil {
		return nil
	}
	out := new(SourceEndpoint)
	in.DeepCopyInto(out)
	return out
}
